// <auto-generated />
using System;
using InternshipPortal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipPortal.API.Migrations
{
    [DbContext(typeof(InternshipPortalContext))]
    [Migration("20251022065200_UpdateToSqlServer")]
    partial class UpdateToSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipPortal.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CertificateIssued")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Progress")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SkillsAcquired")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentInternships")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxInternships")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Frontend Development",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 236, DateTimeKind.Utc).AddTicks(9558),
                            CurrentInternships = 0,
                            IsActive = true,
                            ManagerEmail = "manager@company.com",
                            ManagerId = 5,
                            ManagerName = "Manager Name",
                            MaxInternships = 3,
                            Name = "TechCorp Solutions",
                            Technologies = ""
                        },
                        new
                        {
                            Id = 2,
                            Area = "Backend Development",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 236, DateTimeKind.Utc).AddTicks(9873),
                            CurrentInternships = 0,
                            IsActive = true,
                            ManagerEmail = "john@techcorp.com",
                            ManagerId = 6,
                            ManagerName = "John Smith",
                            MaxInternships = 2,
                            Name = "TechCorp Solutions",
                            Technologies = ""
                        },
                        new
                        {
                            Id = 3,
                            Area = "Data Science",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 236, DateTimeKind.Utc).AddTicks(9876),
                            CurrentInternships = 0,
                            IsActive = true,
                            ManagerEmail = "manager@company.com",
                            ManagerId = 5,
                            ManagerName = "Manager Name",
                            MaxInternships = 4,
                            Name = "DataFlow Inc",
                            Technologies = ""
                        },
                        new
                        {
                            Id = 4,
                            Area = "DevOps",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 236, DateTimeKind.Utc).AddTicks(9879),
                            CurrentInternships = 0,
                            IsActive = true,
                            ManagerEmail = "john@techcorp.com",
                            ManagerId = 6,
                            ManagerName = "John Smith",
                            MaxInternships = 2,
                            Name = "CloudTech",
                            Technologies = ""
                        },
                        new
                        {
                            Id = 5,
                            Area = "Mobile Development",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 236, DateTimeKind.Utc).AddTicks(9882),
                            CurrentInternships = 0,
                            IsActive = true,
                            ManagerEmail = "manager@company.com",
                            ManagerId = 5,
                            ManagerName = "Manager Name",
                            MaxInternships = 3,
                            Name = "InnovateLab",
                            Technologies = ""
                        });
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CertificateStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasShownInterest")
                        .HasColumnType("bit");

                    b.Property<int>("InternshipStatus")
                        .HasColumnType("int");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCompanyId");

                    b.HasIndex("RegNo")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateStatus = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 238, DateTimeKind.Utc).AddTicks(186),
                            HasShownInterest = false,
                            InternshipStatus = 1,
                            RegNo = "2021-Arid-4566",
                            Technology = "Flutter",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CertificateStatus = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 238, DateTimeKind.Utc).AddTicks(536),
                            HasShownInterest = true,
                            InternshipStatus = 1,
                            RegNo = "2021-Arid-4404",
                            Technology = "React Native",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CertificateStatus = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 238, DateTimeKind.Utc).AddTicks(538),
                            HasShownInterest = true,
                            InternshipStatus = 1,
                            RegNo = "2020-Arid-0126",
                            Technology = "React JS",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("InternshipPortal.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RegNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Technology")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(6952),
                            Email = "nauman@admin.com",
                            Name = "M.Nauman",
                            PasswordHash = "Admin123",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(7839),
                            Email = "qadis@student.com",
                            Name = "Qadis Parvez",
                            PasswordHash = "Student456",
                            RegNo = "2021-Arid-4566",
                            Role = 1,
                            Technology = "Flutter"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(7845),
                            Email = "ali@student.com",
                            Name = "Ali Haider",
                            PasswordHash = "Pass789",
                            RegNo = "2021-Arid-4404",
                            Role = 1,
                            Technology = "React Native"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(7848),
                            Email = "daud@student.com",
                            Name = "Daud Ansar",
                            PasswordHash = "Daud2024",
                            RegNo = "2020-Arid-0126",
                            Role = 1,
                            Technology = "React JS"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "TechCorp Solutions",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(8126),
                            Email = "manager@company.com",
                            Name = "Manager Name",
                            PasswordHash = "Manager321",
                            Role = 3,
                            Technology = "Frontend Development"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "TechCorp Solutions",
                            CreatedAt = new DateTime(2025, 10, 22, 6, 51, 58, 235, DateTimeKind.Utc).AddTicks(8131),
                            Email = "john@techcorp.com",
                            Name = "John Smith",
                            PasswordHash = "John@Tech",
                            Role = 3,
                            Technology = "Backend Development"
                        });
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Assignment", b =>
                {
                    b.HasOne("InternshipPortal.API.Models.Company", "Company")
                        .WithMany("Assignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipPortal.API.Models.Student", "Student")
                        .WithMany("Assignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipPortal.API.Models.User", null)
                        .WithMany("Assignments")
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Certificate", b =>
                {
                    b.HasOne("InternshipPortal.API.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipPortal.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipPortal.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Company", b =>
                {
                    b.HasOne("InternshipPortal.API.Models.User", "Manager")
                        .WithMany("ManagedCompanies")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Student", b =>
                {
                    b.HasOne("InternshipPortal.API.Models.Company", "AssignedCompany")
                        .WithMany()
                        .HasForeignKey("AssignedCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InternshipPortal.API.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Company", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.Student", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("InternshipPortal.API.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ManagedCompanies");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
